// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: hris/v1/employee/employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_hris_v1_employee_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hris_v1_employee_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_hris_v1_employee_employee_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Division      string                 `protobuf:"bytes,4,opt,name=division,proto3" json:"division,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_hris_v1_employee_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hris_v1_employee_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_hris_v1_employee_employee_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmployeeResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *EmployeeResponse) GetDivision() string {
	if x != nil {
		return x.Division
	}
	return ""
}

var File_hris_v1_employee_employee_proto protoreflect.FileDescriptor

const file_hris_v1_employee_employee_proto_rawDesc = "" +
	"\n" +
	"\x1fhris/v1/employee/employee.proto\x12\x10hris.v1.employee\"8\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x10EmployeeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition\x12\x1a\n" +
	"\bdivision\x18\x04 \x01(\tR\bdivision2j\n" +
	"\x0fEmployeeService\x12W\n" +
	"\vGetEmployee\x12$.hris.v1.employee.GetEmployeeRequest\x1a\".hris.v1.employee.EmployeeResponseB\x1bZ\x19hris/v1/employee;employeeb\x06proto3"

var (
	file_hris_v1_employee_employee_proto_rawDescOnce sync.Once
	file_hris_v1_employee_employee_proto_rawDescData []byte
)

func file_hris_v1_employee_employee_proto_rawDescGZIP() []byte {
	file_hris_v1_employee_employee_proto_rawDescOnce.Do(func() {
		file_hris_v1_employee_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hris_v1_employee_employee_proto_rawDesc), len(file_hris_v1_employee_employee_proto_rawDesc)))
	})
	return file_hris_v1_employee_employee_proto_rawDescData
}

var file_hris_v1_employee_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hris_v1_employee_employee_proto_goTypes = []any{
	(*GetEmployeeRequest)(nil), // 0: hris.v1.employee.GetEmployeeRequest
	(*EmployeeResponse)(nil),   // 1: hris.v1.employee.EmployeeResponse
}
var file_hris_v1_employee_employee_proto_depIdxs = []int32{
	0, // 0: hris.v1.employee.EmployeeService.GetEmployee:input_type -> hris.v1.employee.GetEmployeeRequest
	1, // 1: hris.v1.employee.EmployeeService.GetEmployee:output_type -> hris.v1.employee.EmployeeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hris_v1_employee_employee_proto_init() }
func file_hris_v1_employee_employee_proto_init() {
	if File_hris_v1_employee_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hris_v1_employee_employee_proto_rawDesc), len(file_hris_v1_employee_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hris_v1_employee_employee_proto_goTypes,
		DependencyIndexes: file_hris_v1_employee_employee_proto_depIdxs,
		MessageInfos:      file_hris_v1_employee_employee_proto_msgTypes,
	}.Build()
	File_hris_v1_employee_employee_proto = out.File
	file_hris_v1_employee_employee_proto_goTypes = nil
	file_hris_v1_employee_employee_proto_depIdxs = nil
}
