// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: hris/v1/payroll/payroll.proto

package payroll

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayrollService_GetPayroll_FullMethodName = "/hris.v1.payroll.PayrollService/GetPayroll"
)

// PayrollServiceClient is the client API for PayrollService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayrollServiceClient interface {
	GetPayroll(ctx context.Context, in *GetPayrollReques, opts ...grpc.CallOption) (*GetPayrollResponse, error)
}

type payrollServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPayrollServiceClient(cc grpc.ClientConnInterface) PayrollServiceClient {
	return &payrollServiceClient{cc}
}

func (c *payrollServiceClient) GetPayroll(ctx context.Context, in *GetPayrollReques, opts ...grpc.CallOption) (*GetPayrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayrollResponse)
	err := c.cc.Invoke(ctx, PayrollService_GetPayroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayrollServiceServer is the server API for PayrollService service.
// All implementations must embed UnimplementedPayrollServiceServer
// for forward compatibility.
type PayrollServiceServer interface {
	GetPayroll(context.Context, *GetPayrollReques) (*GetPayrollResponse, error)
	mustEmbedUnimplementedPayrollServiceServer()
}

// UnimplementedPayrollServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayrollServiceServer struct{}

func (UnimplementedPayrollServiceServer) GetPayroll(context.Context, *GetPayrollReques) (*GetPayrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayroll not implemented")
}
func (UnimplementedPayrollServiceServer) mustEmbedUnimplementedPayrollServiceServer() {}
func (UnimplementedPayrollServiceServer) testEmbeddedByValue()                        {}

// UnsafePayrollServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayrollServiceServer will
// result in compilation errors.
type UnsafePayrollServiceServer interface {
	mustEmbedUnimplementedPayrollServiceServer()
}

func RegisterPayrollServiceServer(s grpc.ServiceRegistrar, srv PayrollServiceServer) {
	// If the following call panics, it indicates UnimplementedPayrollServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayrollService_ServiceDesc, srv)
}

func _PayrollService_GetPayroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayrollReques)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayrollServiceServer).GetPayroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayrollService_GetPayroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayrollServiceServer).GetPayroll(ctx, req.(*GetPayrollReques))
	}
	return interceptor(ctx, in, info, handler)
}

// PayrollService_ServiceDesc is the grpc.ServiceDesc for PayrollService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayrollService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hris.v1.payroll.PayrollService",
	HandlerType: (*PayrollServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayroll",
			Handler:    _PayrollService_GetPayroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hris/v1/payroll/payroll.proto",
}
