// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: hris/v1/payroll/payroll.proto

package payroll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPayrollReques struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayrollReques) Reset() {
	*x = GetPayrollReques{}
	mi := &file_hris_v1_payroll_payroll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayrollReques) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollReques) ProtoMessage() {}

func (x *GetPayrollReques) ProtoReflect() protoreflect.Message {
	mi := &file_hris_v1_payroll_payroll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollReques.ProtoReflect.Descriptor instead.
func (*GetPayrollReques) Descriptor() ([]byte, []int) {
	return file_hris_v1_payroll_payroll_proto_rawDescGZIP(), []int{0}
}

func (x *GetPayrollReques) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPayrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Position      string                 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayrollResponse) Reset() {
	*x = GetPayrollResponse{}
	mi := &file_hris_v1_payroll_payroll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollResponse) ProtoMessage() {}

func (x *GetPayrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hris_v1_payroll_payroll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollResponse.ProtoReflect.Descriptor instead.
func (*GetPayrollResponse) Descriptor() ([]byte, []int) {
	return file_hris_v1_payroll_payroll_proto_rawDescGZIP(), []int{1}
}

func (x *GetPayrollResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPayrollResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPayrollResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_hris_v1_payroll_payroll_proto protoreflect.FileDescriptor

const file_hris_v1_payroll_payroll_proto_rawDesc = "" +
	"\n" +
	"\x1dhris/v1/payroll/payroll.proto\x12\x0fhris.v1.payroll\"\"\n" +
	"\x10GetPayrollReques\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x12GetPayrollResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\tR\bposition2f\n" +
	"\x0ePayrollService\x12T\n" +
	"\n" +
	"GetPayroll\x12!.hris.v1.payroll.GetPayrollReques\x1a#.hris.v1.payroll.GetPayrollResponseB\x19Z\x17hris/v1/payroll;payrollb\x06proto3"

var (
	file_hris_v1_payroll_payroll_proto_rawDescOnce sync.Once
	file_hris_v1_payroll_payroll_proto_rawDescData []byte
)

func file_hris_v1_payroll_payroll_proto_rawDescGZIP() []byte {
	file_hris_v1_payroll_payroll_proto_rawDescOnce.Do(func() {
		file_hris_v1_payroll_payroll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hris_v1_payroll_payroll_proto_rawDesc), len(file_hris_v1_payroll_payroll_proto_rawDesc)))
	})
	return file_hris_v1_payroll_payroll_proto_rawDescData
}

var file_hris_v1_payroll_payroll_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hris_v1_payroll_payroll_proto_goTypes = []any{
	(*GetPayrollReques)(nil),   // 0: hris.v1.payroll.GetPayrollReques
	(*GetPayrollResponse)(nil), // 1: hris.v1.payroll.GetPayrollResponse
}
var file_hris_v1_payroll_payroll_proto_depIdxs = []int32{
	0, // 0: hris.v1.payroll.PayrollService.GetPayroll:input_type -> hris.v1.payroll.GetPayrollReques
	1, // 1: hris.v1.payroll.PayrollService.GetPayroll:output_type -> hris.v1.payroll.GetPayrollResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hris_v1_payroll_payroll_proto_init() }
func file_hris_v1_payroll_payroll_proto_init() {
	if File_hris_v1_payroll_payroll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hris_v1_payroll_payroll_proto_rawDesc), len(file_hris_v1_payroll_payroll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hris_v1_payroll_payroll_proto_goTypes,
		DependencyIndexes: file_hris_v1_payroll_payroll_proto_depIdxs,
		MessageInfos:      file_hris_v1_payroll_payroll_proto_msgTypes,
	}.Build()
	File_hris_v1_payroll_payroll_proto = out.File
	file_hris_v1_payroll_payroll_proto_goTypes = nil
	file_hris_v1_payroll_payroll_proto_depIdxs = nil
}
